name: Vail Stables
favicon: null
layout_spectrum: 0.74867
typography_spectrum: 1
title: 'Vail Stables in Vail, Colorado  (855) Ride-Vail'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d5ccbe'
    - '#919880'
    - '#007bac'
    - '#984f44'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
