name: Vail Stables
favicon: null
layout_spectrum: 0.93573
typography_spectrum: 0.5561746128369123
title: Vail Stables
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edc7af'
    - '#0097b2'
    - '#040015'
    - '#890000'
    - '#dd832e'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
