name: Vail Stables
favicon: null
layout_spectrum: 0.74867
typography_spectrum: 1
title: (855) Ride-Vail or (970) 476-6941
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#211212'
    - '#4b3934'
    - '#7d8a3f'
    - '#b0ad97'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
