name: Vail Stables
favicon: null
layout_spectrum: 0.74867
typography_spectrum: 1
title: (855) Ride-Vail  _______   (970) 476-6941
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d5ccbe'
    - '#919880'
    - '#007bac'
    - '#984f44'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
