name: Vail Stables
favicon: null
layout_spectrum: 0.24729
typography_spectrum: 1
title: Vail Stables
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0c0c'
    - '#505050'
    - '#d0d0d0'
    - '#969696'
    - '#be9b00'
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
