name: Vail Stables
favicon: null
layout_spectrum: 0.93573
typography_spectrum: 0.5561746128369123
title: Vail Stables
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#363638'
    - '#b69361'
    - '#887000'
    - '#e1c700'
    - '#aeb94c'
  brandStrength: 0.025889512384310365
  lightness: 0.04034126945771277
  saturation: 0.9386676831636578
  rhythmicContrast: 0.1393535102251917
purpose: []
