name: Vail Stables
favicon: null
layout_spectrum: 0.21651
typography_spectrum: 0.30578
title: Vail Stables   (855) Ride-Vail
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d5ccbe'
    - '#919880'
    - '#007bac'
    - '#984f44'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
