name: Vail Stables
favicon: null
layout_spectrum: 0.74867
typography_spectrum: 1
title: (855) Ride-Vail    - - - - - -     (970) 476-6941
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#22160a'
    - '#6687a6'
    - '#946b3f'
    - '#ffc066'
    - '#d29441'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
